import { db } from './db.js';

export const TEMPLATES = {
  logo: {
    name: 'Logo',
    hint: 'Marks, wordmarks and brand symbols',
    checklist: ['Write the brief', 'Collect keywords', 'Sketch rough ideas', 'Pick three directions', 'Test in black and white', 'Test at small sizes', 'Finalize and export'],
    zones: ['References', 'Keywords', 'Sketches'],
    stages: ['Rough sketches', 'Directions', 'Refinement', 'Final'],
    features: ['mockups'],
    bg: 'grid',
    tips: ['Sketch more ideas than feels necessary. The tenth one is often better than the first.', 'A good logo still works in one color and at 16 pixels.'],
  },
  illustration: {
    name: 'Illustration',
    hint: 'Drawings, characters and scenes',
    checklist: ['Idea', 'Rough sketch', 'Line art', 'Flat colors', 'Shading', 'Finishing touches'],
    zones: ['Poses', 'Light and mood', 'Color references'],
    stages: ['Idea', 'Rough sketch', 'Line art', 'Flat colors', 'Shading', 'Finish'],
    features: [],
    bg: 'kraft',
    tips: ['Squint at the drawing to check the big shapes and values.', 'Flip the canvas now and then. Mistakes jump out.'],
  },
  ui: {
    name: 'UI / web',
    hint: 'Apps, websites and screens',
    checklist: ['Define the goal and the user', 'List the screens', 'Wireframes', 'Visual design', 'Check contrast and type sizes', 'Collect feedback'],
    zones: ['Screen references', 'Type', 'Components'],
    stages: ['Wireframe', 'Low fidelity', 'High fidelity', 'Final'],
    features: [],
    bg: 'dots',
    tips: ['Body text reads best at 16px or larger.', 'Check every text color against its background in the palette tab.'],
  },
  poster: {
    name: 'Poster / editorial',
    hint: 'Posters, flyers and layouts',
    checklist: ['Gather the content', 'Rank the information', 'Sketch layouts', 'Set the typography', 'Final polish'],
    zones: ['Layouts', 'Type', 'Color'],
    stages: ['Thumbnails', 'Layout', 'Typography', 'Final'],
    features: [],
    bg: 'plain',
    tips: ['Decide what people should read first, second and third before you start.'],
  },
  free: {
    name: 'Free',
    hint: 'A blank project, no steps',
    checklist: [],
    zones: [],
    stages: ['Start', 'Middle', 'Final'],
    features: [],
    bg: 'plain',
    tips: [],
  },
};

export async function getTemplates() {
  const custom = await db.all('templates');
  const out = { ...TEMPLATES };
  custom.forEach((c) => { out[c.id] = c; });
  return out;
}

export const BOARD_BGS = [['plain', 'Plain'], ['grid', 'Grid paper'], ['dots', 'Dot grid'], ['cork', 'Cork board'], ['kraft', 'Kraft paper']];

export const LIBRARY_CATEGORIES = ['Typography', 'Logos', 'Color', 'Illustration', 'Layout', 'UI', 'Photography', 'Other'];

export const PROMPT_SUBJECTS = [
  'a cat napping in a sunbeam', 'your favorite mug', 'a rainy window', 'a tiny house on a hill', 'a hand holding something precious',
  'a houseplant that has seen things', 'your shoes by the door', 'a fox wearing a scarf', 'a crowded bookshelf', 'a bowl of fruit',
  'a street lamp at night', 'a sleepy dragon', 'an old bicycle', 'a cafe table for two', 'an old key', 'a jellyfish',
  'a robot gardener', 'someone waiting for a bus', 'a cloud with feelings', 'a lighthouse', 'a slice of cake', 'your desk right now',
  'a snail on an adventure', 'a pair of glasses', 'a mushroom village', 'a whale in the sky', 'a vintage camera', 'a sleeping dog',
  'a market stall', 'a teapot with a personality', 'a staircase going somewhere strange', 'a pigeon with big plans',
];
export const PROMPT_CONSTRAINTS = [
  'use only three colors', 'no outlines, only shapes', 'draw it from above', 'use one continuous line',
  'use your other hand for the first minute', 'only black and one accent color', 'keep it smaller than your palm',
  'exaggerate the proportions', 'use only straight lines', 'add a pattern somewhere', 'put it in a different season',
  'light it from below', 'draw it as if it were a logo', 'make it cuter than it should be', 'draw it three times, each one simpler',
  'no erasing allowed',
];
export const PROMPT_MINUTES = [10, 15, 20, 30];

// ---------- palette ideas, sorted by purpose ----------
export const PURPOSES = [
  ['illustration', 'Illustration', 'Mix light, mid and dark values, and keep one bright accent for what matters most.'],
  ['logo', 'Logo', 'Two or three colors is plenty. Make sure one is dark, so the logo works in a single color.'],
  ['ui', 'UI / web', 'You need a background, a text color and one main action color. Check text contrast first.'],
  ['poster', 'Poster', 'Go high contrast. One loud color pulls the eye to the most important line.'],
];
export const PURPOSE_OF_TYPE = { logo: 'logo', illustration: 'illustration', ui: 'ui', poster: 'poster' };

// colors: '#HEX' (a cute name is made up automatically) or ['#HEX', 'Name'].
// pick: true = palettes collected from Pinterest, shown under "My picks".
export const PALETTE_IDEAS = [
  { name: 'Picnic Blanket Noon', purposes: ['illustration'], colors: ['#0D3B66', '#F95738', '#EE964B', '#F4D35E', '#FAF0CA'] },
  { name: 'Mossy Fable', purposes: ['illustration'], colors: ['#2F4F3E', '#6B8F71', '#A0613F', '#C9B79C', '#E8D9B5'] },
  { name: 'Cloud Nap', purposes: ['illustration'], colors: ['#C9B8E8', '#F7C6D9', '#BFE0F5', '#B5EAD7', '#FFF1A6'] },
  { name: 'Lantern Alley', purposes: ['illustration'], colors: ['#1E2350', '#4450B8', '#F07C66', '#FFD166', '#F4F1DE'] },
  { name: 'Cinnamon Steep', purposes: ['illustration'], colors: ['#5A3B2E', '#A0613F', '#D9772B', '#E8B04B', '#EFE6D8'] },
  { name: 'Tide Pool Siesta', purposes: ['illustration'], colors: ['#1F6F78', '#3BA3A6', '#A3D9D0', '#F2E8CF', '#E07A5F'] },
  { name: 'Red Stamp', purposes: ['logo'], colors: ['#121212', '#D7263D', '#FAF8F5'] },
  { name: 'Corner Roastery', purposes: ['logo'], colors: ['#3E2723', '#C68E5A', '#E3CDB3'] },
  { name: 'Mint Leaf Label', purposes: ['logo'], colors: ['#0F4C3A', '#8FD3B0', '#FFFFFF'] },
  { name: 'Indigo Lemon Desk', purposes: ['logo'], colors: ['#2B2724', '#4450B8', '#FFF1A6'] },
  { name: 'Yellow Awning', purposes: ['logo'], colors: ['#1A1A1A', '#F6C700', '#FFFFFF'] },
  { name: 'Jam Jar Label', purposes: ['logo'], colors: ['#6E1E4E', '#F4A6B8', '#FFF8F2'] },
  { name: 'Quiet Desk', purposes: ['ui'], colors: ['#2B2724', '#4450B8', '#FFF1A6', '#FFFFFF', '#FAF8F5'] },
  { name: 'Midnight Lamp', purposes: ['ui'], colors: ['#1C1B22', '#25242C', '#8B96F0', '#F5E27A', '#ECE9E4'] },
  { name: 'Fresh Sheets', purposes: ['ui'], colors: ['#1B2B3A', '#1F6F78', '#E07A5F', '#FFFFFF', '#F5F8FA'] },
  { name: 'Paper Bag Shop', purposes: ['ui'], colors: ['#3A2E2A', '#B4532E', '#F2C14E', '#FFFFFF', '#FFF8F2'] },
  { name: 'Sprout Morning', purposes: ['ui'], colors: ['#1E2D24', '#2E7D4F', '#F4A261', '#FFFFFF', '#F4FAF6'] },
  { name: 'Amp Feedback', purposes: ['poster'], colors: ['#111111', '#FF3B30', '#FFE600', '#FFFFFF'] },
  { name: 'Grid and Red', purposes: ['poster'], colors: ['#1A1A1A', '#E63312', '#F2F0E9'] },
  { name: 'Summer Carnival', purposes: ['poster'], colors: ['#264653', '#2A9D8F', '#E9C46A', '#F4A261', '#E76F51'] },
  { name: 'Ink Drum', purposes: ['poster'], colors: ['#0078BF', '#FF48B0', '#FFE800', '#F7F3EA'] },
  { name: 'Opening Night', purposes: ['poster'], colors: ['#0B132B', '#5BC0BE', '#FFD23F', '#F8F9FA'] },

  // ---- My picks (from Pinterest) ----
  { pick: true, name: 'Matcha Love Letter', purposes: ['logo', 'poster'], colors: [['#40733A', 'Matcha'], ['#A6C673', 'Matcha Latte'], ['#F9829E', 'Heart Pink'], ['#FAD3E5', 'Sakura Milk']] },
  { pick: true, name: 'Triple Scoop', purposes: ['illustration', 'ui'], colors: [['#604734', 'Chocolate'], ['#FCF7D9', 'Vanilla'], ['#F6D8D6', 'Strawberry Cream'], ['#F0C5D4', 'Bubblegum']] },
  { pick: true, name: 'Cherry Slice Afternoon', purposes: ['illustration', 'poster'], colors: [['#B01013', 'Crimson Red'], ['#A2B9D5', 'Baby Blue'], ['#F4F2E2', 'Vanilla Cream'], ['#AACCB1', 'Mint Green']] },
  { pick: true, name: 'Mint Chip Cone', purposes: ['illustration', 'ui'], colors: [['#684F48', 'Cocoa'], ['#D6E9ED', 'Mint Ice'], ['#CCD6D6', 'Silver Mist'], ['#F9E7C7', 'Custard']] },
  { pick: true, name: 'Plum Butter Toast', purposes: ['logo', 'poster'], colors: [['#700143', 'Royal Purple'], ['#CFD78C', 'Citron'], ['#F9F6BD', 'Butter']] },
  { pick: true, name: 'Prune and Terracotta', purposes: ['logo', 'poster'], colors: [['#412143', 'Prune'], ['#E0653F', 'Brique'], ['#FFEEBA', 'Lin']] },
  { pick: true, name: 'Sticker Drawer', purposes: ['illustration', 'ui'], colors: [['#EEEFE8', 'Alabaster'], ['#B8C9DB', 'Columbia Blue'], ['#E9ACBB', 'Cherry Blossom Pink'], ['#8FBC93', 'Cambridge Blue'], ['#FCEBBF', 'Peach']] },
  { pick: true, name: 'Rusty Bicycle', purposes: ['poster', 'logo'], colors: [['#BA3801', 'Rust'], ['#FFEC89', 'Butter'], ['#4A69B3', 'Navy']] },
  { pick: true, name: 'Mulberry Jam Matcha', purposes: ['ui', 'illustration'], colors: [['#A6C4A0', 'Matcha'], ['#B14052', 'Mulberry'], ['#FFE4ED', 'Blush Milk'], ['#FEF8F0', 'Milky Silk']] },
  { pick: true, name: 'Lavender Latte Desk', purposes: ['illustration', 'ui'], colors: [['#CABCCD', 'Thistle'], ['#F8F3EC', 'Parchment'], ['#B5C99A', 'Muted Olive'], ['#4D3329', 'Dark Coffee']] },
  { pick: true, name: 'Raspberry Shortbread', purposes: ['illustration'], colors: [['#DCD3AA', 'Sugar Cookie'], ['#CD5782', 'Wild Raspberry'], ['#C7DAD8', 'Morning Mist'], ['#F0EEF3', 'Mallow Fluff']] },
  { pick: true, name: 'Blueberry Soda Float', purposes: ['poster', 'illustration'], colors: [['#F2619C', 'Raspberry Rose'], ['#E7BEF8', 'Soft Lilac'], ['#93ABD9', 'Blueberry Milk'], ['#EDE986', 'Lemon Cream']] },
  { pick: true, name: 'Brass Watering Can', purposes: ['illustration', 'poster'], colors: [['#A6B13C', 'Brass'], ['#F1E69F', 'Butter Yellow'], ['#FB9FC5', 'Illusion'], ['#AA9FBE', 'Pastel Purple']] },
  { pick: true, name: 'Last Train Home', purposes: ['illustration', 'ui'], colors: [['#FCB5D0', 'Powder Pink'], ['#626283', 'Dolphin'], ['#929073', 'Artichoke'], ['#E7E0C1', 'Pearl']] },
  { pick: true, name: 'Peach Ribbon', purposes: ['ui', 'illustration'], colors: [['#F8F7FF', 'Ghost White'], ['#FFEEDD', 'Antique White'], ['#FFD8BE', 'Peach Fuzz'], ['#B8B8FF', 'Periwinkle'], ['#9381FF', 'Soft Periwinkle']] },
  { pick: true, name: 'Copper Patina Party', purposes: ['ui', 'poster'], colors: [['#F2FFE9', 'Honeydew'], ['#F2A4D8', 'Blush Pop'], ['#E5C5D2', 'Pastel Petal'], ['#30A496', 'Verdigris'], ['#005F87', 'Baltic Blue']] },
  { pick: true, name: 'Starry Bedroom', purposes: ['ui', 'illustration'], colors: [['#DAE8FB', 'Alice Blue'], ['#F2D2FF', 'Thistle'], ['#75CBD1', 'Pearl Aqua'], ['#3E5BA3', 'Dusk Blue'], ['#0C0D45', 'Deep Navy']] },
  { pick: true, name: 'Mossy Window Frost', purposes: ['ui', 'poster'], colors: [['#E6FBDA', 'Frosted Mint'], ['#FFF8D2', 'Lemon Chiffon'], ['#84D175', 'Moss Green'], ['#3E5BA3', 'Dusk Blue'], ['#0C2D45', 'Deep Space Blue']] },
  { pick: true, name: 'Clover Field', purposes: ['ui'], colors: [['#CAFFA6', 'Spring Meadow'], ['#204654', 'Teal Waters'], ['#A9E0F1', 'Glacial Sky'], ['#F7F9E1', 'Morning Mist']] },
  { pick: true, name: 'Lilac Kite', purposes: ['ui', 'illustration'], colors: [['#E5F8F0', 'Honeydew'], ['#ECFFBE', 'Tea Green'], ['#BCA4F5', 'Mauve'], ['#81CFFF', 'Sky Blue'], ['#4A69CE', 'Royal Blue']] },
  { pick: true, name: 'Crystal Shop', purposes: ['illustration', 'ui'], colors: [['#E5EBF8', 'Alice Blue'], ['#BEFFEA', 'Icy Aqua'], ['#F4A4F5', 'Plum'], ['#9881FF', 'Soft Periwinkle'], ['#A94ACE', 'Amethyst']] },
  { pick: true, name: 'Fairground Pink', purposes: ['poster', 'illustration'], colors: [['#EDF8E5', 'Honeydew'], ['#E8FFBE', 'Tea Green'], ['#FFB8E3', 'Blush Pop'], ['#FF819C', 'Cotton Candy'], ['#CE4A4A', 'Blushed Brick']] },
  { pick: true, name: 'Willow Shade', purposes: ['illustration', 'ui'], colors: [['#F0F7EA', 'Honeydew'], ['#FFFAE0', 'Cornsilk'], ['#EEE59F', 'Vanilla Custard'], ['#AAD480', 'Willow Green'], ['#75C97F', 'Emerald']] },
  { pick: true, name: 'Sunny Pillow', purposes: ['illustration', 'ui'], colors: [['#FFF2B2', 'Buttercup Sky'], ['#A8C6E7', 'Dewy Blue'], ['#FFE08A', 'Sunwashed'], ['#FFF7D6', 'Cloud Puff'], ['#7FA8D6', 'Morning Breeze']] },
  { pick: true, name: 'Kiwi Bento', purposes: ['illustration'], colors: [['#9DBF7C', 'Matcha Mist'], ['#C7DDAA', 'Linden Leaf'], ['#FFF2A6', 'Sunny Citron'], ['#E6F0C3', 'Kiwi Cream'], ['#A7BC9A', 'Green Tea Latte']] },
  { pick: true, name: 'Petal Mocha', purposes: ['illustration', 'ui'], colors: [['#443025', 'Dark Chocolate'], ['#7F5836', 'Aloewood'], ['#AA7F66', 'Milk Tea'], ['#EC9C9D', 'Sakura'], ['#F2CFCA', 'Misty Rose']] },
  { pick: true, name: 'Hanami Path', purposes: ['illustration', 'poster'], colors: [['#AFC867', 'Meadow'], ['#5E504B', 'Bark'], ['#DD839B', 'Cotton Candy'], ['#EEB1CB', 'Pink Lemonade'], ['#F1CFD3', 'Rose Quartz']] },
  { pick: true, name: 'Blue Ink Lemon', purposes: ['logo', 'poster'], colors: [['#0D21A5', 'Zaffre'], ['#B9C7F8', 'Periwinkle'], ['#D1D067', 'Citron']] },
  { pick: true, name: 'Rainy Garage', purposes: ['illustration', 'ui'], colors: [['#8BE8CB', 'Aquamarine'], ['#7EA2AA', 'Cool Steel'], ['#888DA7', 'Lavender Grey'], ['#9C7A97', 'Dusty Mauve'], ['#303633', 'Gunmetal']] },
  { pick: true, name: 'Papaya Jam', purposes: ['illustration', 'poster'], colors: [['#FFECCC', 'Papaya Whip'], ['#F2D0A4', 'Apricot Cream'], ['#C8D6AF', 'Tea Green'], ['#A4303F', 'Cherry Rose'], ['#870058', 'Dark Raspberry']] },
  { pick: true, name: 'Plum Orchard', purposes: ['illustration', 'ui'], colors: [['#F5FBDA', 'Light Yellow'], ['#D9EFBD', 'Tea Green'], ['#B9D175', 'Willow Green'], ['#A33E79', 'Berry Blush'], ['#450C3F', 'Midnight Violet']] },
  { pick: true, name: 'Herb Shelf', purposes: ['illustration'], colors: [['#FDDDC6', 'Powder Petal'], ['#AA7E8E', 'Dusty Mauve'], ['#A7A488', 'Dry Sage'], ['#ABD299', 'Celadon'], ['#5D5041', 'Stone Brown']] },
  { pick: true, name: 'Wisteria Rain', purposes: ['ui', 'illustration'], colors: [['#EAF7ED', 'Honeydew'], ['#E0FAFF', 'Light Cyan'], ['#9FE2EE', 'Frosted Blue'], ['#80A4D4', 'Wisteria Blue'], ['#7B75C9', 'Medium Slate Blue']] },
  { pick: true, name: 'Seashell Vanity', purposes: ['ui', 'illustration'], colors: [['#F7F4EA', 'Floral White'], ['#DED9E2', 'Lavender'], ['#C0B9DD', 'Periwinkle'], ['#80A1D4', 'Wisteria Blue'], ['#75C9C8', 'Pearl Aqua']] },
  { pick: true, name: 'Fizzy Arcade', purposes: ['poster', 'ui'], colors: [['#4B52EB', 'Blue Ribbon'], ['#D0ED40', 'Pear'], ['#C7BFEF', 'Periwinkle'], ['#F92D97', 'Wild Strawberry'], ['#F0E7E4', 'Dawn Pink'], ['#141213', 'Woodsmoke']] },
  { pick: true, name: 'Linen Pantry', purposes: ['logo', 'illustration'], colors: [['#7B2A26', 'Brick Rust'], ['#525C44', 'Olive Moss'], ['#A39384', 'Soft Taupe'], ['#E4DFD3', 'Linen Cream']] },
  { pick: true, name: 'Oat Matcha Bar', purposes: ['logo', 'ui'], colors: [['#76845B', 'Matcha'], ['#D8D3B3', 'Oat Milk'], ['#603314', 'Espresso'], ['#B1B7BE', 'Cloud']] },
  { pick: true, name: 'Midnight Petal', purposes: ['ui', 'poster'], colors: [['#16131F', 'Back in Black'], ['#F0D9E4', 'Mountain Heather'], ['#C1A0AC', 'Decanting'], ['#4A3F4B', 'Funkie Friday'], ['#806C79', 'Moonscape']] },
  { pick: true, name: 'Blue Hour Ink', purposes: ['logo', 'ui'], colors: [['#020202', 'Slate Gray'], ['#B2D5E5', 'Candy Blue'], ['#1F2634', 'Blue Atoll']] },
  { pick: true, name: 'Bakery Envelope', purposes: ['logo', 'ui'], colors: [['#B1C8EA', 'Envelope Blue'], ['#FFEBAA', 'Butter'], ['#382322', 'Chocolate Chip'], ['#FDEBDE', 'Dough']] },
  { pick: true, name: 'Syrup Sunday', purposes: ['illustration', 'logo'], colors: [['#FFF8CA', 'Lemon Chiffon'], ['#CDE3E8', 'Botticelli'], ['#6B0B0C', 'Rosewood'], ['#2D120D', 'Coffee Bean']] },
  { pick: true, name: 'Wasabi Sunset', purposes: ['poster', 'ui'], colors: [['#E9F056', 'Wasabi'], ['#FF5C34', 'Orange Topaze'], ['#D7EFFF', 'Cool Blue'], ['#351E28', 'Cassis'], ['#AEB8A0', 'Vert Sauge']] },
  { pick: true, name: 'Rainboot Garden', purposes: ['illustration', 'ui'], colors: [['#D1EFBD', 'Matcha Latte'], ['#89D385', 'Botanist'], ['#6CD1F0', 'Aquamarine'], ['#A1A1F7', 'Grape Soda'], ['#EFCCEA', 'Pink Diamond']] },
  { pick: true, name: 'Guacamole Party', purposes: ['poster', 'illustration'], colors: [['#A8FF70', 'Lime'], ['#00883E', 'Avocado'], ['#FFB8E7', 'Pretty Pink'], ['#FFDAA2', 'Peach Fuzz'], ['#092E00', 'Forest']] },
  { pick: true, name: 'Grape Bubblegum', purposes: ['poster', 'illustration'], colors: [['#FF76B7', 'Barbie Pink'], ['#E2C6FE', 'Lavender'], ['#FFA981', 'Peach'], ['#9E1F63', 'Grape'], ['#FFD3F7', 'Pastel Pink']] },
  { pick: true, name: 'Slushie Machine', purposes: ['poster', 'ui'], colors: [['#D0FFA4', 'Powdered Lime'], ['#000181', 'Night Skies'], ['#E8A0FF', 'Violet'], ['#006EE9', 'Blue Raspberry'], ['#83E7FF', 'Sunny Skies']] },
  { pick: true, name: 'Neon Truck Stop', purposes: ['poster', 'illustration'], colors: [['#C1ECFD', 'Icy Blue'], ['#F70A36', 'Primary Red'], ['#283F76', 'Midnight'], ['#5591D1', 'Tufts Blue'], ['#FFF6B7', 'Buttercream']] },
  { pick: true, name: 'Comic Corner', purposes: ['poster', 'illustration'], colors: [['#E36D9B', 'Watermelon'], ['#E7DD6A', 'Canary'], ['#A0CB75', 'Limeade'], ['#10B183', 'Emerald'], ['#2B4789', 'Royal Blue']] },
  { pick: true, name: 'Wind-Up Toybox', purposes: ['illustration'], colors: [['#957A63', 'Saddle Brown'], ['#1FB1B9', 'Turquoise'], ['#CCC6AC', 'Desert Tan'], ['#E7A8C7', 'Baby Pink'], ['#EC326F', 'Barbie']] },
  { pick: true, name: 'Stationery Haul', purposes: ['illustration', 'ui'], colors: [['#ECF3E9', 'Avalanche'], ['#EFDFBE', 'Dough'], ['#F6B6BD', 'Princess'], ['#D17B92', 'Tickle Me Pink'], ['#356BA4', 'Maritime']] },
  { pick: true, name: 'Flower Stall Morning', purposes: ['illustration', 'ui'], colors: [['#877499', 'Heather'], ['#679F9F', 'Viridian'], ['#E6D4BF', 'Sandstone'], ['#E18299', 'Candy'], ['#7EADDB', 'Azur']] },
  { pick: true, name: 'Velvet Evening', purposes: ['logo', 'ui'], colors: [['#223662', 'Rhino'], ['#B9A5D2', 'London Hue'], ['#E0BAAA', 'Cashmere'], ['#261834', 'Bleached Cedar']] },
  { pick: true, name: 'Oak Shade', purposes: ['illustration'], colors: [['#C3C88C', 'Sage'], ['#30253E', 'Dark Purple'], ['#638872', 'Russian Green'], ['#80B9B1', 'Pewter Blue'], ['#94C7B4', 'Cambridge Blue']] },
  { pick: true, name: 'Frozen Pier', purposes: ['ui', 'illustration'], colors: [['#F0ECDD', 'Moonlight'], ['#8BA3C5', 'Frost Blue'], ['#495B7D', 'Steel'], ['#23354D', 'Storm'], ['#02122F', 'Oxford Blue']] },
  { pick: true, name: 'Peach Snowfall', purposes: ['illustration', 'ui'], colors: [['#525871', 'Concrete'], ['#857C91', 'Warm Steel'], ['#CD9FA0', 'Rosewood'], ['#F2C1A3', 'Peaches and Cream'], ['#F8CCAA', 'Dawn']] },
  { pick: true, name: 'Crosswalk Glow', purposes: ['poster', 'illustration'], colors: [['#F1444E', 'Vermillion'], ['#FFAE81', 'Honeydew'], ['#C9947A', 'Fawn'], ['#4B536B', 'Blue Spruce'], ['#212934', 'Asphalt']] },
  { pick: true, name: 'Wet Pavement', purposes: ['illustration', 'poster'], colors: [['#C5C0AA', 'Dark Vanilla'], ['#7F3025', 'Burnt Umber'], ['#44201C', 'Temptress'], ['#4D8A8B', 'Wintergreen Dream'], ['#83B8A2', 'Dark Sea Green']] },
  { pick: true, name: 'Petal Bench', purposes: ['illustration', 'ui'], colors: [['#2B181E', 'Raisin Black'], ['#C8A8B6', 'Silver Pink'], ['#ECC3A5', 'Desert Sand'], ['#D88084', 'New York Pink'], ['#A65665', 'Deep Puce']] },
  { pick: true, name: 'Cocoa Scoop', purposes: ['illustration', 'logo'], colors: [['#2E211C', 'Raisin Black'], ['#9CB8B7', 'Cambridge Blue'], ['#EAE0C7', 'Pearl'], ['#C06226', 'Ruddy Brown'], ['#984619', 'Saddle Brown']] },
  { pick: true, name: 'Newsstand Recess', purposes: ['illustration', 'ui'], colors: [['#BAC47D', 'Pistachio'], ['#5DB1C8', 'Tropical Waters'], ['#AFC0C2', 'Spearmint'], ['#D997BD', 'Blush'], ['#2D5265', 'Jungle']] },
  { pick: true, name: 'Seaside Shack', purposes: ['illustration', 'poster'], colors: [['#554345', 'Coffee'], ['#D463A1', 'Orchid'], ['#EEC7A0', 'Sugar Cookie'], ['#7FB9B9', 'Seafoam Green'], ['#6CAEDE', 'Sky']] },
  { pick: true, name: 'Lagoon Snorkel', purposes: ['illustration', 'poster'], colors: [['#2073C3', 'Bright Marine'], ['#98B62D', 'Lime Moss'], ['#7DDEB5', 'Aquamarine'], ['#4DC9AE', 'Turquoise'], ['#838A7E', 'Grey Olive']] },
  { pick: true, name: 'Neon Lime Alley', purposes: ['poster', 'logo'], colors: [['#E42217', 'Lava Red'], ['#A9ED3D', 'Lemon Lime'], ['#34CD3F', 'Fresh Green'], ['#081910', 'Black Bean']] },
  { pick: true, name: 'Golden Stairwell', purposes: ['poster', 'logo'], colors: [['#BA0101', 'Guardsman Red'], ['#E99D25', 'Golden Bell'], ['#ADD794', 'Pale Olive Green'], ['#040011', 'Jaguar']] },
  { pick: true, name: 'Mossy Gold Tango', purposes: ['poster', 'logo'], colors: [['#032B52', 'Prussian Blue'], ['#ACC291', 'Light Moss Green'], ['#CBAF2B', 'Old Gold'], ['#032C30', 'Firefly']] },
  { pick: true, name: 'Midnight Snack Bar', purposes: ['poster', 'illustration'], colors: [['#D56CC0', 'Sky Magenta'], ['#77EAC9', 'Light Teal'], ['#BA0101', 'Guardsman Red'], ['#123524', 'Phthalo Green']] },
  { pick: true, name: 'Grapefruit Splash', purposes: ['poster', 'illustration'], colors: [['#FF7070', 'Grapefruit Pink'], ['#DF4436', 'Cinnabar'], ['#FF783E', 'Atomic Tangerine'], ['#884039', 'Clay Soil'], ['#4C3535', 'Deep Mocha']] },
  { pick: true, name: 'Striped Awning', purposes: ['logo', 'poster'], colors: [['#70271F', 'Coffee'], ['#CCE5FF', 'Ice Cube'], ['#F24E07', 'Mango'], ['#F9F5E6', 'Oat Milk'], ['#26422B', 'Cambodia']] },
  { pick: true, name: 'Rose Dust', purposes: ['ui', 'illustration'], colors: [['#FFDBDA', 'Soft Blush'], ['#DB7F8E', 'Old Rose'], ['#D5C5C8', 'Pale Slate'], ['#9DA3A4', 'Cool Steel'], ['#604D53', 'Taupe Grey']] },
  { pick: true, name: 'Pastel Lobby', purposes: ['illustration', 'ui'], colors: [['#F7D7CD', 'Gold Pink'], ['#D79B95', 'Berry Blush'], ['#984343', 'Pastel Maroon'], ['#91BDC2', 'Cherub'], ['#F1E4D9', 'Cashmere']] },
  { pick: true, name: 'Sandy Porch', purposes: ['illustration', 'ui'], colors: [['#7C5337', 'Burnt Ochre'], ['#6E9BA0', 'Dull Cyan'], ['#BEE1D8', 'Cute Mint'], ['#FAE9B7', 'Astra'], ['#F9EDDC', 'Evergreen Pearl']] },
  { pick: true, name: 'Cliffside Hush', purposes: ['ui', 'illustration'], colors: [['#493A35', 'Van Dyke'], ['#8185A4', 'Cool Gray'], ['#EAC8AF', 'Desert Sand'], ['#758E90', 'Slate Gray'], ['#203C49', 'Charcoal']] },
  { pick: true, name: 'Golden Tide', purposes: ['illustration', 'poster'], colors: [['#353B56', 'Delft Blue'], ['#7D7585', 'Taupe Gray'], ['#FBB45E', 'Earth Yellow'], ['#C99379', 'Persian Orange'], ['#251211', 'Licorice']] },
  { pick: true, name: 'Seaside Rail', purposes: ['illustration', 'ui'], colors: [['#017360', 'Pacific Green'], ['#446E8F', 'Rainy Lake'], ['#77A7C4', 'Serene Sea'], ['#A1DBF1', 'Sora Blue'], ['#F2E6CE', 'Afterglow'], ['#F3D094', 'Bungalow Maple']] },
  { pick: true, name: 'Leafy Ceiling', purposes: ['illustration'], colors: [['#6C9B76', 'Aquadulce'], ['#97C49E', 'Aroma Green'], ['#CDE8D4', 'Winter Mist'], ['#BAD17A', 'Tarragon'], ['#80A32F', 'Antique Moss'], ['#657E47', 'Chalet Green']] },
  { pick: true, name: 'Citrus Orchard', purposes: ['illustration', 'logo'], colors: [['#FBD271', 'Lemonade'], ['#0F4E77', 'Sea Blue'], ['#89A377', 'Matcha'], ['#E7BD8B', 'Honey Drizzle'], ['#372516', 'Coffee Grounds']] },
  { pick: true, name: 'Silk Pajamas', purposes: ['ui'], colors: [['#F4F2E0', 'Beige'], ['#F3D5CF', 'Champagne Pink'], ['#CCC3C0', 'Pale Silver'], ['#A5ABAB', 'Metallic Silver']] },
  { pick: true, name: 'Blank Canvas Morning', purposes: ['ui'], colors: [['#6C6C6A', 'Dim Gray'], ['#E8CCD7', 'Queen Pink'], ['#DEE5ED', 'Azureish White'], ['#FFFBF0', 'Floral White']] },
  { pick: true, name: 'Foggy Notebook', purposes: ['ui', 'logo'], colors: [['#A8B5C1', 'Fog Blue'], ['#E3E6EA', 'Porcelain Mist'], ['#B9AABF', 'Lavender'], ['#8C8F91', 'Ashwood Grey'], ['#3C3F4A', 'Faded Ink']] },
  { pick: true, name: 'Dried Bouquet', purposes: ['logo', 'ui'], colors: [['#4F4832', 'Deep Olive'], ['#B1B0A7', 'Stone Grey'], ['#C9A9A6', 'Dust Rose'], ['#D8C8A3', 'Golden Smoke'], ['#2C2C2C', 'Ink Black']] },
  { pick: true, name: 'Ink Rose', purposes: ['ui', 'logo'], colors: [['#0E181E', 'Gunmetal'], ['#2E4756', 'Charcoal'], ['#F9EBE0', 'Linen'], ['#CB98AA', 'Rose'], ['#8C5F66', 'Taupe']] },
  { pick: true, name: 'Autumn Leaf Study', purposes: ['illustration', 'ui'], colors: [['#25344F', 'Space Cadet'], ['#617891', 'Slate Gray'], ['#D5B893', 'Tan'], ['#6F4D38', 'Coffee'], ['#632024', 'Caput Mortuum']] },
  { pick: true, name: 'Dewy Petals', purposes: ['illustration', 'ui'], colors: [['#A9C46C', 'Fresh Green'], ['#5F7A4F', 'Deep Moss'], ['#F2C6CF', 'Light Blush'], ['#FFFDF8', 'Warm White']] },
  { pick: true, name: 'Peony Teacup', purposes: ['illustration', 'ui'], colors: [['#FDE5E8', 'Valerie'], ['#E7B4B9', 'Amazon River Dolphin'], ['#A4565C', 'Lingonberry Punch'], ['#E8F0A2', 'Primrose'], ['#999D4F', 'Lazy Lizard']] },
  { pick: true, name: 'Carousel Lights', purposes: ['poster', 'illustration'], colors: [['#210100', 'Bistre'], ['#E6A341', 'Goldfinch'], ['#FECE79', 'Butter'], ['#B14A36', 'Indian Red'], ['#8C0902', 'Garnet']] },
  { pick: true, name: 'Teddy Bear Window', purposes: ['illustration', 'ui'], colors: [['#F8E3C4', 'Oat Milk'], ['#F0C283', 'Pollen'], ['#5D6973', 'Graphite'], ['#CF6E6C', 'Love Potion'], ['#DCA7A1', 'Ballerina']] },
  { pick: true, name: 'Snowy Alley', purposes: ['ui', 'illustration'], colors: [['#D6D0CC', 'Smoked Oyster'], ['#593E3A', 'Shaved Chocolate'], ['#6E6B7A', 'Space Station'], ['#40445A', 'Midnight Sky'], ['#211E25', 'Noble Black']] },
  { pick: true, name: 'Cherry Pit Lagoon', purposes: ['illustration', 'poster'], colors: [['#F1E379', 'Pale Amber'], ['#D0E1CB', 'Honeydew'], ['#87BBA2', 'Muted Teal'], ['#5D737E', 'Blue Slate'], ['#500303', 'Black Cherry']] },
  { pick: true, name: 'Coral Popsicle', purposes: ['poster', 'illustration'], colors: [['#F6FFEA', 'Honeydew'], ['#FFDE96', 'Soft Peach'], ['#FA855A', 'Coral Glow'], ['#C93638', 'Tomato Jam'], ['#62C4DA', 'Sky Blue']] },
  { pick: true, name: 'Electric Ballet', purposes: ['poster', 'ui'], colors: [['#054FF0', 'Electric Blue'], ['#F9F8F3', 'Eggshell'], ['#000000', 'Black'], ['#E1D2F3', 'Frosty Grape'], ['#DCFC73', 'Hi-Vis']] },
  { pick: true, name: 'Red Kite Sky', purposes: ['poster', 'ui'], colors: [['#BA1200', 'Brick Ember'], ['#031927', 'Ink Black'], ['#508AA8', 'Air Force Blue'], ['#9DD1F1', 'Baby Blue'], ['#C8E0F4', 'Pale Sky']] },
  { pick: true, name: 'Melon Soda Coast', purposes: ['illustration', 'poster'], colors: [['#F4F1BB', 'Lemon Chiffon'], ['#E6EBE0', 'Soft Linen'], ['#9BC1BC', 'Ash Grey'], ['#36C9C6', 'Strong Cyan'], ['#ED6A5A', 'Vibrant Coral']] },
  { pick: true, name: 'Toffee Icicle', purposes: ['illustration', 'logo'], colors: [['#F5FFE9', 'Honeydew'], ['#A4E1F2', 'Frosted Blue'], ['#AFD6D1', 'Light Blue'], ['#A46030', 'Toffee Brown'], ['#870002', 'Blood Red']] },
  { pick: true, name: 'Pink Hedge', purposes: ['illustration', 'logo'], colors: [['#E38792', 'Cotton Candy'], ['#4E0A0B', 'Garnet'], ['#F2EEE8', 'Dusty White'], ['#9DAD71', 'Khaki']] },
  { pick: true, name: 'Hot Pepper Tutu', purposes: ['poster', 'logo'], colors: [['#AA0003', 'Chilli'], ['#FFA1C2', 'Hot Rose'], ['#FFD6DE', 'Ballet Slipper'], ['#FFF3B2', 'Lemon']] },
  { pick: true, name: 'Gingham Cherries', purposes: ['logo', 'poster'], colors: [['#FFF8E7', 'Cosmic Latte'], ['#930500', 'Sangria'], ['#95BBEA', 'Cornflower']] },
  { pick: true, name: 'Soft Rinse', purposes: ['ui', 'illustration'], colors: [['#F2F6F7', 'Cleansed'], ['#80ECF2', 'Shower'], ['#59B5F6', 'Joust Blue'], ['#5D94E6', 'Dodger Blue'], ['#3467B5', 'Denim'], ['#DB89DD', 'Violaceous']] },
  { pick: true, name: 'Beach Ball Splash', purposes: ['poster', 'illustration'], colors: [['#227E9D', 'Pool Bottom'], ['#51ACC5', 'Dragonfly'], ['#96D0D2', 'Lifeboat Blue'], ['#FDF9FA', 'Abalone'], ['#FDA5CC', 'Cotton Candy'], ['#FD50A4', 'Barbie Pink']] },
  { pick: true, name: 'Magenta Rush', purposes: ['poster', 'ui'], colors: [['#FFF3F2', 'Snow'], ['#FFCAE4', 'Pastel Petal'], ['#F10291', 'Electric Rose'], ['#89235B', 'Dark Raspberry'], ['#250209', 'Rich Mahogany']] },
  { pick: true, name: 'Wheatfield Twilight', purposes: ['ui', 'illustration'], colors: [['#FFF4EB', 'Seashell'], ['#F6E0B6', 'Wheat'], ['#A6BCC9', 'Powder Blue'], ['#3E4B8E', 'French Blue'], ['#3D1534', 'Midnight Violet']] },
  { pick: true, name: 'Painted Fence', purposes: ['illustration'], colors: [['#596498', 'Kashmir Blue'], ['#D2E8AE', 'Light Sage'], ['#739CBD', 'Blue Koi'], ['#B3DCD6', 'Sea Mist'], ['#447D51', 'Cactus']] },
  { pick: true, name: 'Paprika Terrace', purposes: ['logo', 'illustration'], colors: [['#B53324', 'Hot Paprika'], ['#E5A657', 'Honeycomb'], ['#DFBC94', 'Biscuit'], ['#F5E2CE', 'Crumpet']] },
  { pick: true, name: 'Ornament Glow', purposes: ['illustration', 'poster'], colors: [['#792C18', 'Cocoa Spice'], ['#FDC371', 'Warm Eggnog'], ['#9B7A30', 'Mossy Pine'], ['#554224', 'Green Ember']] },
  { pick: true, name: 'Sunbleached Linen', purposes: ['ui', 'logo'], colors: [['#AECCC3', 'Opal'], ['#C5BA8D', 'Indian Khaki'], ['#F7F3F0', 'Spring Wood'], ['#111111', 'Cod Gray']] },
  { pick: true, name: 'Tiled Shower', purposes: ['ui', 'poster'], colors: [['#016283', 'Deep Ocean Blue'], ['#9DABB6', 'Slate Gray'], ['#E2DBE2', 'Lavender Mist'], ['#98CDB1', 'Seafoam Green'], ['#060200', 'Jet Black']] },
  { pick: true, name: 'Sherbet Swirl', purposes: ['illustration', 'ui'], colors: [['#FF99C8', 'Carnation Pink'], ['#FCF6BD', 'Lemon Chiffon'], ['#D0F4DE', 'Nyanza'], ['#A9DEF9', 'Uranian Blue'], ['#E4C1F9', 'Mauve']] },
  { pick: true, name: 'Strawberry Velvet', purposes: ['logo', 'ui'], colors: [['#420D19', 'Berry'], ['#F6BAD6', 'Milkshake'], ['#F1D3DF', 'Strawberry Sorbet'], ['#2F020C', 'Rotten Cherry'], ['#741E31', 'Strawberry Smoothie']] },
  { pick: true, name: 'Marshmallow Mug', purposes: ['logo', 'ui'], colors: [['#E8DBCC', 'Oat Milk'], ['#5F0C2F', 'Favorite Mug'], ['#3C0E18', 'Dark Chocolate'], ['#EAADC1', 'Cherry Marshmallow']] },
  { pick: true, name: 'Strawberry Field Day', purposes: ['illustration', 'poster'], colors: [['#E24B5A', 'Strawberry Red'], ['#F06C78', 'Berry Rose'], ['#F9C3CB', 'Blush Pink'], ['#F6E7B8', 'Seed Cream'], ['#8E9A5A', 'Leaf Olive Green']] },
  { pick: true, name: 'Frosting Swirl', purposes: ['ui', 'logo'], colors: [['#EBE9DD', 'Coconut Milk'], ['#A8A696', 'Sage'], ['#D4C7AF', 'Warm Beige'], ['#766B5D', 'Taupe Brown']] },
  { pick: true, name: 'Wool Sock Sunday', purposes: ['ui', 'logo'], colors: [['#4F5153', "Davy's Grey"], ['#CACED2', 'American Silver'], ['#7C7376', 'Sonic Silver'], ['#6E5353', 'Wenge'], ['#6B4145', 'Deep Coffee']] },
  { pick: true, name: 'Glossy Loafers', purposes: ['logo', 'illustration'], colors: [['#A0381B', 'Deep Dumpling'], ['#56433C', 'Liver Chestnut'], ['#8B9A9F', 'Morning Blue'], ['#D2C7BA', 'Pale Silver'], ['#AD8261', 'Café au Lait']] },
  { pick: true, name: 'Cheers at Noon', purposes: ['poster', 'ui'], colors: [['#BACCCE', 'Loblolly'], ['#353534', 'Tuatara'], ['#6E3928', 'Pickled Bean'], ['#66A2B4', 'Hippie Blue'], ['#D4872D', 'Brandy Punch']] },
];
